### ISSUE TITLE
please slim build

### ISSUE THREAD

**Issue by Marcos-Dtel** [mytja/treble_evo#1]
Please build a slim version with less google gapps, unnecessary gapps that we can download from the playstore, for the simple reason that several partitions do not support the giant size of this GSI

**Comment by Kevinco1** [comment]
I second this, initial build is too large to fit into existing system partition

**Comment by mitzamike** [comment]
I also second this, we need a "light" version. The current version of the GSI is quite laggy sometimes on my SM-A536B compared to the LineageOS GSI which runs smoother. It's understandable though, since this GSI got a lot more features but I think some unnecessary stuff can be removed to achieve better performance.

**Comment by mytja** [comment]
Added in newest release. Thanks for all the comments.

https://github.com/mytja/treble_evo/releases/tag/20240905
