### ISSUE TITLE
what does dsu loader exactly do?

### ISSUE THREAD

**Issue by Mod4-Da-GOAT** [mytja/treble_evo#103]
because I do not really understand (btw sry for asking bcs the contributors are not really active in their forum)

**Comment by mytja** [comment]
Please stop opening issues for such minor questions that are completely unrelated to this project. Ask those questions in general Android support forums or just Google them:

https://github.com/VegaBobo/DSU-Sideloader?tab=readme-ov-file#about-dsu

To generally sum it up & simplify it, DSU creates a separate system partition on the disk, meaning that your original system partition is left untouched. This means that you can have your stable system installed permanently (let's say OneUI) and a GSI installed in DSU mode. You can boot at any time in and out of DSU system and if the DSU system suddenly stops working, it'll automatically throw you back into your main/stable (OneUI) system. It's great for testing GSIs so that you can see whether features are working or not.

**Comment by Mod4-Da-GOAT** [comment]
ok mb I will not open issues for unrelated questions again and thank you for answering my question
