### ISSUE TITLE
RMX3800

### ISSUE THREAD

**Issue by devdaw6** [mytja/treble_evo#24]
When playing, YouTube crashes, any YouTube

**Comment by mytja** [comment]
I'll assume that's an issue with your YouTube app and not with GMS unless you provide logs using `adb logcat`.

**Comment by devdaw6** [comment]
I have a fingerprint on the screen, so it requires me to touch the button, if you need any information to help me, I will be happy to help you

**Comment by devdaw6** [comment]
[Uploading logcat.txt…]()

**Comment by mytja** [comment]
Logcat hasn't uploaded...

Phh Settings > Samsung features has a setting that enables what you want. Check if your device settings also have something similar, otherwise it's hard to do anything.

![Screenshot_20240920-103701_PhhTrebleApp.png](https://github.com/user-attachments/assets/48f39131-bec4-42d3-98cd-273d43603286)

**Comment by devdaw6** [comment]
I have a realme gt6, I don't have these sections

**Comment by devdaw6** [comment]
I tried to remake my finger for my device, but I have little experience, I don't know what files and where to get them from, I tried to change build.prop but it didn't help

**Comment by Kevinco1** [comment]
> I have a realme gt6, I don't have these sections

As stated, this is for Samsung devices not Realme

**Comment by Kevinco1** [comment]
I'm also experiencing System UI crashes while trying to play any vid through YouTube (ReVanced Magisk version) 

My device is Samsung SM-X200, Tab A8 running 906 slim build. I'll try to send logcats
