### ISSUE TITLE
Device bootloping and recovery not working in galaxy f23 5g

### ISSUE THREAD

**Issue by Mozahid007** [mytja/treble_evo#81]
I was using 9.5 beta Gsi just fine. Then I changed the boot animation from Evolver to 2 Sims in the phh Treble settings. After some time, suddenly, my device froze and went into a boot loop state. And I'm unable to boot into recovery also. Recovery gets frozen in the welcome screen and then the device boot loops

**Comment by mytja** [comment]
"2 SIMs" seems to be absent in Evolution X 9.6. Was it really present in 9.5?

![Screenshot_20241206-234830_Nastavitve.png](https://github.com/user-attachments/assets/d4dac25c-0037-4f99-a871-e9ee157495ab)

Evolution X sometimes has a hard time finding a specific boot animation for unknown reasons. I'll try to fix it in an upcoming December update. That's likey why it's bootlooping.

As for recovery, it's a completely separate Android system and has nothing to do with default Android installation (in this case Evolution X). Even the kernel is different. That's why I find it hard that your recovery cannot boot due to an issue with base system. Maybe try to reflash recovery through Odin?

**Comment by Mozahid007** [comment]
Yes, there were options for selecting 1,2,3 sims present in 9.5. I tried flashing recovery again but no luck. Saw an earlier closed thread about boot animation might be the issue of the boot loop. Eventually, I had to flash stock oneui and reflash Evox to get my device working.  

Also, there's no in-call audio in Sim2. Everything works fine with Sim 1. Is it a common gsi issue in Samsung? Is there any fix for the in-call audio in Sim 2?
