### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by Trommel2** [mytja/treble_evo#87]
I am completely new to this and this is my first attempt at building my own GSI_ROM. The November version of Mytja works very well on my Unihertz Pocket. That's why I want to build my own ROM to customize the hardware keyboard even better.

[100% 1/1] analyzing Android.bp files and generating ninja file at out/soong/build.treble_arm64_bgN.ninja
FAILED: out/soong/build.treble_arm64_bgN.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     --soong_variables out/soong/soong.treble_arm64_bgN.variables -o out/soong/build.treble_arm64_bgN.ninja --globListDir treble_arm64_bgN --globFile out/soong/globs-treble_arm64_bgN.ninja -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.treble_arm64_bgN.build Android.bp
Killed
06:40:24 soong bootstrap failed with: exit status 1
ninja: build stopped: subcommand failed.

#### failed to build some targets (01:33 (mm:ss)) ####
__________________________________________________________________________________________________________________________________________
The compilation process ends with “soong bootstrap failed with: exit Status1 
ninja: build stopped: subcommand failed.” 
All previous process steps were successful. Where do I have to check or change something?

**Comment by mytja** [comment]
That log is not useful. Was there anything more displayed to it or was this it?

I'm thinking WSL is at fault somehow.

It might be either:
1. WSL has a strange filesystem root `/` (not that likely)
2. OOM killer is killing make (very likely, especially as it's Ubuntu 22.04) - see https://github.com/microsoft/WSL/issues/10199 for the solution.
3. Something else that I'm unaware of.

In either case, please make sure you have at least 300GB (maybe even 400GB) of free space allocated to WSL and at least 12GB RAM with zram (and huge swap file), so that in the end you have around 64GB of RAM.

I've also found this article if it's in any help: https://www.effie.io/post/building-aosp-on-windows-with-wsl2-part-1/

**Comment by Trommel2** [comment]
Thank you for your quick response. I will read up on the articles.
