### ISSUE TITLE
[UI] Media control seeker waving got minor cursed between EvoX VIII GSI

### ISSUE THREAD

**Issue by Vad1mCSO2** [mytja/treble_evo#9]
![Screenshot_20240906-231955_Gyawun Music](https://github.com/user-attachments/assets/4a3650ae-ca6f-461f-84bc-577145c5ad62)
This is latest EvoX IX
![Screenshot_20240906-231903_Photos](https://github.com/user-attachments/assets/307d84c5-1f9b-4db5-8dc5-110ebe7f9d7e)
This is EvoX VIII looked perfectly

**Comment by mytja** [comment]
I can't see any differences apart from my build having that wave even after the seek indicator.

If that's the issue, ask Evolution X maintainers about it, because that has nothing to do with this specific build or GSI. It's likely intentional. If that's not the issue, please provide more information.
