### ISSUE TITLE
List of Bugs I found in my device 

### ISSUE THREAD

**Issue by Technical06** [mytja/treble_evo#97]
Hii , dev i've been using your build from a while now , and you develop good builds and keep an eye on the issues tab , thanks for that
im providing a list of bugs so that it helps you resolve it.

Device : Realme Narzo 30 Pro 5G
Processor : Mediatek Dimensity 800U
Kernel Version : 4.14+

BUGS : 
1. Network traffic indicator not working from quite some time in every A14 build
2. Bluetooth is also not working and yes i tried 9.7 version too , its still broken 
3. DSU sideloader is not working idk why it is , the error is failed to create partition , is it because of the RO build?

Feature Request : 
1. If possible please add a custom launcher in the next build
2. Also make an RW build , it will fit in my device ,

If you want i can help you with testing purposes 

Thanks 💖, Merry Christmas
Keep up the good work

**Comment by mytja** [comment]
Hey, hope you're having a nice day. Let's go through the issues.

> Network traffic indicator not working from quite some time in every A14 build

I do have some issues stating that traffic indicator isn't working, but I couldn't reproduce it. I promise I'll have a look at the source code and maybe I'll be able to find something (or not...)

Note to self: Implementation at https://github.com/Evolution-X/frameworks_base/commit/0a27948255df6f5c5a0a0a2ad4953322e00ccd55

> Bluetooth is also not working and yes i tried 9.7 version too , its still broken

Bluetooth might still be broken, as stated in the EDIT within the build release, so maybe wait for a couple of days? Does it work on any other GSI? If so, please let me know the names so that I can have a look at their patches.

> DSU sideloader is not working idk why it is , the error is failed to create partition , is it because of the RO build?

DSU Sideloader does not in any way fail if a build is RO. Would you mind sharing details of DSU Sideloader failing?

> If possible please add a custom launcher in the next build

Which custom launcher? You can always download launchers from sources such as Google Play, F-Droid, GitHub and you can install them as standalone apps for the most part.

It's not easy to maintain multiple launchers, not to mention that that would increase build sizes, which I'm trying to avoid as sizes are already massive.

Note that the Evolution X launcher has been dead for quite some time now. It would likely need a lot of rework to get it to function in the Android 14 QPR3 state, as well as adapt it to LineageOS sources. That's the work I'm not willing to put in.

And the final reason is that I'd like to keep this GSI as close to Evolution X experience and a custom launcher would make this far from vanilla.

Of course you may also at any time opt into using Magisk modules that enable the functionality/custom launcher you want. Or if anybody would like to fork this project and maintain multi-launcher support, you're absolutely free to do so.

> Also make an RW build , it will fit in my device ,

I'm actually not sure of the benefits of RW builds in the age of Magisk, KernelSU, APatch and other highly developed systemless solutions that can achieve the same thing as a RW build can. I won't build a specific RW build as that'd only extend my build time, achieving literally nothing when it comes to rooted users, but you are free to make it RW yourself by using the following instructions:

https://github.com/ahnet-69/treble_yaap/blob/14.0/Make-rw.md

That's it from me for now. Have a nice day. :)

**Comment by Technical06** [comment]
> Hey, hope you're having a nice day. Let's go through the issues.
> 
> > Network traffic indicator not working from quite some time in every A14 build
> 
> I do have some issues stating that traffic indicator isn't working, but I couldn't reproduce it. I promise I'll have a look at the source code and maybe I'll be able to find something (or not...)
> 
> Note to self: Implementation at [Evolution-X/frameworks_base@0a27948](https://github.com/Evolution-X/frameworks_base/commit/0a27948255df6f5c5a0a0a2ad4953322e00ccd55)
> 
> > Bluetooth is also not working and yes i tried 9.7 version too , its still broken
> 
> Bluetooth might still be broken, as stated in the EDIT within the build release, so maybe wait for a couple of days? Does it work on any other GSI? If so, please let me know the names so that I can have a look at their patches.
Bluetooth is working in every A13 builds , and in the older A14 builds 
Im dropping a link here for you : https://github.com/KoysX/treble_build_evo/releases

> 
> > DSU sideloader is not working idk why it is , the error is failed to create partition , is it because of the RO build?
> 
> DSU Sideloader does not in any way fail if a build is RO. Would you mind sharing details of DSU Sideloader failing?
It says it fails to create system partition , although it does not fail in A13 , in the recent A14 builds problem started to occour

> 
> > If possible please add a custom launcher in the next build
> 
> Which custom launcher? You can always download launchers from sources such as Google Play, F-Droid, GitHub and you can install them as standalone apps for the most part.
I tried some systemless magisk module launchers , but that doesnt seem to work . launcher starts to crash . i just want custom launcher to show ram usage like in Lawnchair 3 , superior launcher 

> 
> It's not easy to maintain multiple launchers, not to mention that that would increase build sizes, which I'm trying to avoid as sizes are already massive.
> 
> Note that the Evolution X launcher has been dead for quite some time now. It would likely need a lot of rework to get it to function in the Android 14 QPR3 state, as well as adapt it to LineageOS sources. That's the work I'm not willing to put in.
> 
> And the final reason is that I'd like to keep this GSI as close to Evolution X experience and a custom launcher would make this far from vanilla.
> 
> Of course you may also at any time opt into using Magisk modules that enable the functionality/custom launcher you want. Or if anybody would like to fork this project and maintain multi-launcher support, you're absolutely free to do so.
> 
> > Also make an RW build , it will fit in my device ,
> 
> I'm actually not sure of the benefits of RW builds in the age of Magisk, KernelSU, APatch and other highly developed systemless solutions that can achieve the same thing as a RW build can. I won't build a specific RW build as that'd only extend my build time, achieving literally nothing when it comes to rooted users, but you are free to make it RW yourself by using the following instructions:

I just wanted an RW build because i wanted to modify something in the system ( build.prop ) , to make some system images fit into my super , i deleted every my_xxx partition , which caused to make boot times larger upto 4 minutes and 20 seconds , so i searched for a fix 
First i found a fix using build prop , but that doesnt seem to work , so now , replaced those my_xxx partitions with empty my_xxx partition so that they just pass boot checks and does not increase boot times , now i have lots of space in my super partition while maintaining boot speed ( now boots in just 50 seconds ) , i set the size of partitions to 2 MB so that it just passes bootloader checks

> 
> https://github.com/ahnet-69/treble_yaap/blob/14.0/Make-rw.md
> 
> That's it from me for now. Have a nice day. :)

Same to you , have a nice day :)

**Comment by mytja** [comment]
> Network traffic indicator not working from quite some time in every A14 build

I've looked into it, and it seems as if your kernel isn't properly reporting network stats, as they need eBPF to function, which is a feature in newer 5.x+ kernels. If I remember correctly, BPF was already a nuisance during A14 QPRs.

Officially, supported kernel versions for A14 and A15 are 4.19+.

I've tried migrating off to a different data collection API, but it has just reported plain wrong information ([also reported by others](https://forum.earlybird.club/threads/networkstatsmanager-querysummaryfordevice-strange-results.1305066/)).

There's not much that can be done from my side, which is unfortunate.

> Bluetooth is also not working and yes i tried 9.7 version too , its still broken

Please try again with the latest version: https://github.com/mytja/treble_evo/releases/tag/20241225

I can't guarantee Bluetooth will work, but you have higher chances of it working. Try flashing it in DSU Sideloader first.

>> DSU Sideloader does not in any way fail if a build is RO. Would you mind sharing details of DSU Sideloader failing?
>
> It says it fails to create system partition , although it does not fail in A13 , in the recent A14 builds problem started to occour

I've had DSU fail because an image extract wasn't divisible by 1024 (or something similar?). Maybe check that your image isn't corrupted.
